2017-05-28 22:57:20 [scrapy] INFO: Scrapy 1.0.3 started (bot: Topgoods)
2017-05-28 22:57:20 [scrapy] INFO: Optional features available: ssl, http11, boto
2017-05-28 22:57:20 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'Topgoods.spiders', 'SPIDER_MODULES': ['Topgoods.spiders'], 'LOG_FILE': 'scrapy.log', 'BOT_NAME': 'Topgoods'}
2017-05-28 22:57:20 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState
2017-05-28 22:57:21 [boto] DEBUG: Retrieving credentials from metadata server.
2017-05-28 22:57:22 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
2017-05-28 22:57:22 [boto] ERROR: Unable to read instance data, giving up
2017-05-28 22:57:22 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2017-05-28 22:57:22 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2017-05-28 22:57:22 [twisted] CRITICAL: Unhandled error in Deferred:
2017-05-28 22:57:22 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/yang/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 71, in crawl
    self.engine = self._create_engine()
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 83, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/lib/python2.7/dist-packages/scrapy/core/engine.py", line 67, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/core/scraper.py", line 70, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 56, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 32, in from_settings
    mwcls = load_object(clspath)
  File "/usr/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named Images
2017-05-28 22:58:41 [scrapy] INFO: Scrapy 1.0.3 started (bot: Topgoods)
2017-05-28 22:58:41 [scrapy] INFO: Optional features available: ssl, http11, boto
2017-05-28 22:58:41 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'Topgoods.spiders', 'SPIDER_MODULES': ['Topgoods.spiders'], 'LOG_FILE': 'scrapy.log', 'BOT_NAME': 'Topgoods'}
2017-05-28 22:58:41 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState
2017-05-28 22:58:41 [boto] DEBUG: Retrieving credentials from metadata server.
2017-05-28 22:58:42 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
2017-05-28 22:58:42 [boto] ERROR: Unable to read instance data, giving up
2017-05-28 22:58:42 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2017-05-28 22:58:42 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2017-05-28 22:58:42 [twisted] CRITICAL: Unhandled error in Deferred:
2017-05-28 22:58:42 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/yang/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 71, in crawl
    self.engine = self._create_engine()
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 83, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/lib/python2.7/dist-packages/scrapy/core/engine.py", line 67, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/core/scraper.py", line 70, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 56, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 32, in from_settings
    mwcls = load_object(clspath)
  File "/usr/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named Images
2017-05-28 23:01:12 [scrapy] INFO: Scrapy 1.0.3 started (bot: Topgoods)
2017-05-28 23:01:12 [scrapy] INFO: Optional features available: ssl, http11, boto
2017-05-28 23:01:12 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'Topgoods.spiders', 'SPIDER_MODULES': ['Topgoods.spiders'], 'LOG_FILE': 'scrapy.log', 'BOT_NAME': 'Topgoods'}
2017-05-28 23:01:12 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState
2017-05-28 23:01:12 [boto] DEBUG: Retrieving credentials from metadata server.
2017-05-28 23:01:13 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
2017-05-28 23:01:13 [boto] ERROR: Unable to read instance data, giving up
2017-05-28 23:01:13 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2017-05-28 23:01:13 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2017-05-28 23:01:13 [twisted] CRITICAL: Unhandled error in Deferred:
2017-05-28 23:01:13 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/yang/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 71, in crawl
    self.engine = self._create_engine()
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 83, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/lib/python2.7/dist-packages/scrapy/core/engine.py", line 67, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/core/scraper.py", line 70, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 56, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 32, in from_settings
    mwcls = load_object(clspath)
  File "/usr/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named Images
2017-05-28 23:02:33 [scrapy] INFO: Scrapy 1.0.3 started (bot: Topgoods)
2017-05-28 23:02:33 [scrapy] INFO: Optional features available: ssl, http11, boto
2017-05-28 23:02:33 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'Topgoods.spiders', 'SPIDER_MODULES': ['Topgoods.spiders'], 'LOG_FILE': 'scrapy.log', 'BOT_NAME': 'Topgoods'}
2017-05-28 23:02:33 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState
2017-05-28 23:02:34 [boto] DEBUG: Retrieving credentials from metadata server.
2017-05-28 23:02:35 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
2017-05-28 23:02:35 [boto] ERROR: Unable to read instance data, giving up
2017-05-28 23:02:35 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2017-05-28 23:02:35 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2017-05-28 23:02:35 [twisted] CRITICAL: Unhandled error in Deferred:
2017-05-28 23:02:35 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/yang/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 71, in crawl
    self.engine = self._create_engine()
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 83, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/lib/python2.7/dist-packages/scrapy/core/engine.py", line 67, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/core/scraper.py", line 70, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 56, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 32, in from_settings
    mwcls = load_object(clspath)
  File "/usr/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named Images
2017-05-28 23:08:30 [scrapy] INFO: Scrapy 1.0.3 started (bot: Topgoods)
2017-05-28 23:08:30 [scrapy] INFO: Optional features available: ssl, http11, boto
2017-05-28 23:08:30 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'Topgoods.spiders', 'FEED_URI': 'abc.csv', 'SPIDER_MODULES': ['Topgoods.spiders'], 'BOT_NAME': 'Topgoods', 'FEED_FORMAT': 'csv', 'LOG_FILE': 'scrapy.log'}
2017-05-28 23:08:30 [scrapy] INFO: Enabled extensions: CloseSpider, FeedExporter, TelnetConsole, LogStats, CoreStats, SpiderState
2017-05-28 23:08:30 [boto] DEBUG: Retrieving credentials from metadata server.
2017-05-28 23:08:31 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
2017-05-28 23:08:31 [boto] ERROR: Unable to read instance data, giving up
2017-05-28 23:08:31 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2017-05-28 23:08:31 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2017-05-28 23:08:31 [twisted] CRITICAL: Unhandled error in Deferred:
2017-05-28 23:08:31 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/yang/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 71, in crawl
    self.engine = self._create_engine()
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 83, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/lib/python2.7/dist-packages/scrapy/core/engine.py", line 67, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/core/scraper.py", line 70, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 56, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 32, in from_settings
    mwcls = load_object(clspath)
  File "/usr/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named Images
2017-05-28 23:35:37 [scrapy] INFO: Scrapy 1.0.3 started (bot: Topgoods)
2017-05-28 23:35:37 [scrapy] INFO: Optional features available: ssl, http11, boto
2017-05-28 23:35:37 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'Topgoods.spiders', 'SPIDER_MODULES': ['Topgoods.spiders'], 'LOG_ENABLED': False, 'LOG_FILE': 'scrapy.log', 'BOT_NAME': 'Topgoods'}
2017-05-28 23:35:48 [scrapy] INFO: Scrapy 1.0.3 started (bot: Topgoods)
2017-05-28 23:35:48 [scrapy] INFO: Optional features available: ssl, http11, boto
2017-05-28 23:35:48 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'Topgoods.spiders', 'SPIDER_MODULES': ['Topgoods.spiders'], 'LOG_ENABLED': False, 'LOG_FILE': 'scrapy.log', 'BOT_NAME': 'Topgoods'}
2017-05-28 23:35:52 [scrapy] INFO: Scrapy 1.0.3 started (bot: Topgoods)
2017-05-28 23:35:52 [scrapy] INFO: Optional features available: ssl, http11, boto
2017-05-28 23:35:52 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'Topgoods.spiders', 'SPIDER_MODULES': ['Topgoods.spiders'], 'LOG_FILE': 'scrapy.log', 'BOT_NAME': 'Topgoods'}
2017-05-28 23:35:52 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState
2017-05-28 23:35:52 [boto] DEBUG: Retrieving credentials from metadata server.
2017-05-28 23:35:53 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
2017-05-28 23:35:53 [boto] ERROR: Unable to read instance data, giving up
2017-05-28 23:35:53 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2017-05-28 23:35:53 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2017-05-28 23:35:53 [twisted] CRITICAL: Unhandled error in Deferred:
2017-05-28 23:35:53 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/yang/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 71, in crawl
    self.engine = self._create_engine()
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 83, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/lib/python2.7/dist-packages/scrapy/core/engine.py", line 67, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/core/scraper.py", line 70, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 56, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 32, in from_settings
    mwcls = load_object(clspath)
  File "/usr/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named Images
2017-05-28 23:36:50 [scrapy] INFO: Scrapy 1.0.3 started (bot: Topgoods)
2017-05-28 23:36:50 [scrapy] INFO: Optional features available: ssl, http11, boto
2017-05-28 23:36:50 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'Topgoods.spiders', 'SPIDER_MODULES': ['Topgoods.spiders'], 'LOG_FILE': 'scrapy.log', 'BOT_NAME': 'Topgoods'}
2017-05-28 23:36:50 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState
2017-05-28 23:36:50 [boto] DEBUG: Retrieving credentials from metadata server.
2017-05-28 23:36:51 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
2017-05-28 23:36:51 [boto] ERROR: Unable to read instance data, giving up
2017-05-28 23:36:51 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2017-05-28 23:36:51 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2017-05-28 23:36:51 [twisted] CRITICAL: Unhandled error in Deferred:
2017-05-28 23:36:51 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/yang/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 71, in crawl
    self.engine = self._create_engine()
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 83, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/lib/python2.7/dist-packages/scrapy/core/engine.py", line 67, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/core/scraper.py", line 70, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 56, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 32, in from_settings
    mwcls = load_object(clspath)
  File "/usr/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named Images
2017-05-28 23:42:08 [scrapy] INFO: Scrapy 1.0.3 started (bot: Topgoods)
2017-05-28 23:42:08 [scrapy] INFO: Optional features available: ssl, http11, boto
2017-05-28 23:42:08 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'Topgoods.spiders', 'SPIDER_MODULES': ['Topgoods.spiders'], 'LOG_FILE': 'scrapy.log', 'BOT_NAME': 'Topgoods'}
2017-05-28 23:42:08 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState
2017-05-28 23:42:09 [boto] DEBUG: Retrieving credentials from metadata server.
2017-05-28 23:42:10 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
2017-05-28 23:42:10 [boto] ERROR: Unable to read instance data, giving up
2017-05-28 23:42:10 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2017-05-28 23:42:10 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2017-05-28 23:42:10 [twisted] CRITICAL: Unhandled error in Deferred:
2017-05-28 23:42:10 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/yang/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 71, in crawl
    self.engine = self._create_engine()
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 83, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/lib/python2.7/dist-packages/scrapy/core/engine.py", line 67, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/core/scraper.py", line 70, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 56, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 32, in from_settings
    mwcls = load_object(clspath)
  File "/usr/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named Images
2017-05-28 23:52:09 [scrapy] INFO: Scrapy 1.0.3 started (bot: Topgoods)
2017-05-28 23:52:09 [scrapy] INFO: Optional features available: ssl, http11, boto
2017-05-28 23:52:09 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'Topgoods.spiders', 'SPIDER_MODULES': ['Topgoods.spiders'], 'LOG_FILE': 'scrapy.log', 'BOT_NAME': 'Topgoods'}
2017-05-28 23:52:09 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState
2017-05-28 23:52:09 [boto] DEBUG: Retrieving credentials from metadata server.
2017-05-28 23:52:10 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
2017-05-28 23:52:10 [boto] ERROR: Unable to read instance data, giving up
2017-05-28 23:52:10 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2017-05-28 23:52:10 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2017-05-28 23:52:10 [twisted] CRITICAL: Unhandled error in Deferred:
2017-05-28 23:52:10 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/yang/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 71, in crawl
    self.engine = self._create_engine()
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 83, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/lib/python2.7/dist-packages/scrapy/core/engine.py", line 67, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/core/scraper.py", line 70, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 56, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 32, in from_settings
    mwcls = load_object(clspath)
  File "/usr/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named Images
2017-05-28 23:55:30 [scrapy] INFO: Scrapy 1.0.3 started (bot: Topgoods)
2017-05-28 23:55:30 [scrapy] INFO: Optional features available: ssl, http11, boto
2017-05-28 23:55:30 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'Topgoods.spiders', 'SPIDER_MODULES': ['Topgoods.spiders'], 'LOG_FILE': 'scrapy.log', 'BOT_NAME': 'Topgoods'}
2017-05-28 23:55:30 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, LogStats, CoreStats, SpiderState
2017-05-28 23:55:30 [boto] DEBUG: Retrieving credentials from metadata server.
2017-05-28 23:55:31 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
2017-05-28 23:55:31 [boto] ERROR: Unable to read instance data, giving up
2017-05-28 23:55:31 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2017-05-28 23:55:31 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2017-05-28 23:55:31 [twisted] CRITICAL: Unhandled error in Deferred:
2017-05-28 23:55:31 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/yang/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 71, in crawl
    self.engine = self._create_engine()
  File "/usr/lib/python2.7/dist-packages/scrapy/crawler.py", line 83, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/lib/python2.7/dist-packages/scrapy/core/engine.py", line 67, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/core/scraper.py", line 70, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 56, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/lib/python2.7/dist-packages/scrapy/middleware.py", line 32, in from_settings
    mwcls = load_object(clspath)
  File "/usr/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named Images
